### ISSUE TITLE
Error while unzipping files

### ISSUE THREAD

**Issue by lowpita** [eltreum0/elvuiloginandcharacterselect#1]
Hey. Thank you for the update and the work you put into these textures :) As of today's update there seems to be an error while trying to unzip some of the files from the Blue and Grey folders from Retail, did'nt try with Classic and Wrath. The Red texutes folder is working fine for unzipping and loading in-game.

**Comment by eltreum0** [comment]
I just reextracted and its fine, what do you mean by issue? Did you delete the old files?

**Comment by hellsy55** [comment]
This is what happens when trying to extract specific folders that's no the red textures one:

![image](https://user-images.githubusercontent.com/14031869/202343714-a8413642-b9bc-4ebe-a73c-7c83c2b37fce.png)

**Comment by eltreum0** [comment]
my recommendation is redownloading the file, or maybe cloning this repo

might be worth checking your 7zip version as well

**Comment by hellsy55** [comment]
I had this same error while using PeaZip and WinRAR too, don't think it's a 7zip thing. Worked around it extracting all the files and moving the folders I wanted to load in-game.

**Comment by eltreum0** [comment]
> I had this same error while using PeaZip and WinRAR too, don't think it's a 7zip thing. Worked around it extracting all the files and moving the folders I wanted to load in-game.

its very strange because i didnt have this issue. Where did you download it from? Could be my upload got corrupted there, or maybe it was your download

**Comment by hellsy55** [comment]
I got it from: https://www.tukui.org/addons.php?id=202
Can I find it elsewhere?

**Comment by eltreum0** [comment]
i have it on tukui and wowinterface, let me try reuploading to tukui

**Comment by hellsy55** [comment]
Hi. I tried downloading and unzipping the files from wowinterface and had the same error. Also happened with the reupload from tukui. Only way to avoid that is by unzipping all the files into 1 place and copying/moving the ones I want to load into the game. This problem doesn't seem to happen if I use windows unzipping tools (explorer).

**Comment by eltreum0** [comment]
if it doesnt happen with explorer unzip it might be an issue with 7zip then. I recommend either checking for a possible future version of 7zip that fixes it or just using the regular windows unzip to extract the files for now
