### ISSUE TITLE
Missing folders

### ISSUE THREAD

**Issue by Daptonic** [eltreum0/elvuiloginandcharacterselect#3]
Hey there ... I downloaded the last version (3.1.7) and it seems that some of the folders previously included don't seem to be there. is that expected?

Before: 
- AddOns
- Buttons
- CHATFRAME
- COMMON
- FrameGeneral
- friendsframe
- Glues
- HELPFRAME
- Interface
- **lfgframe**
- MacroFrame
- options
- **optionsframe**
- **PaperDollInfoFrame**
- **STORE**
- Tooltips
- **Vehicles**

After:
- AddOns
- Buttons
- CHATFRAME
- COMMON
- FrameGeneral
- friendsframe
- Glues
- HELPFRAME
- Interface
- MacroFrame
- options
- Tooltips

**Comment by eltreum0** [comment]
yes, they are no longer needed, but you can keep them if you want
